spring:
   datasource:
      username: car_dealership
      password: car_dealership
      url: jdbc:mysql://localhost:3306/car_dealership
   
   jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      defer-datasource-intialization: true
   
   sql:
     init:
       mode: always
       